# backend/api/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    TestView, HealthCheckView, FuelTypeViewSet, StationViewSet, StationFuelViewSet,
    RegisterView, LoginView, CheckEmailAvailability, CheckUsernameAvailability,
    UserListView, UserBlockToggleView,
    FavoriteListCreateView, FavoriteDeleteView,
    ReviewListCreateView,
    OfflinePackageListCreateView, OfflinePackageDeleteView,
    NearbyStationsView
)

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'fuel_types', FuelTypeViewSet)
router.register(r'stations', StationViewSet)
router.register(r'station_fuels', StationFuelViewSet)

# Note: this file is included from the project `core/urls.py` under the
# 'api/' prefix. Do NOT re-include 'api.urls' here (that caused a
# recursion error). Paths below should be relative to the 'api/' prefix.

urlpatterns = [
    # Authentication Paths (mounted at /api/auth/... from the project urls)
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/check-email/', CheckEmailAvailability.as_view(), name='check_email'),
    path('auth/check-username/', CheckUsernameAvailability.as_view(), name='check_username'),
    
    # Test endpoint (available at /api/test/)
    path('test/', TestView.as_view(), name='test-view'),
    
    # Health check endpoint
    path('health/', HealthCheckView.as_view(), name='health-check'),
    
    # Admin user management
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/<int:user_id>/toggle-block/', UserBlockToggleView.as_view(), name='user-toggle-block'),
    
    # Favorites
    path('favorites/', FavoriteListCreateView.as_view(), name='favorite-list-create'),
    path('favorites/<int:station_id>/', FavoriteDeleteView.as_view(), name='favorite-delete'),
    
    # Reviews
    path('reviews/', ReviewListCreateView.as_view(), name='review-list-create'),
    
    # Offline packages
    path('offline-packages/', OfflinePackageListCreateView.as_view(), name='offline-package-list-create'),
    path('offline-packages/<int:package_id>/', OfflinePackageDeleteView.as_view(), name='offline-package-delete'),
    
    # Nearby stations
    path('nearby/', NearbyStationsView.as_view(), name='nearby-stations'),

    # Include all routes generated by DRF's router (e.g. /api/fuel_types/)
    path('', include(router.urls)),
]